/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedPatientRouteImport } from './routes/_authenticated/patient'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin.departments'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated/admin.people'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedDoctorIndexRouteImport } from './routes/_authenticated/doctor.index'
import { Route as AuthenticatedDoctorEmergencyRouteImport } from './routes/_authenticated/doctor.emergency'
import { Route as AuthenticatedPatientIndexRouteImport } from './routes/_authenticated/patient.index'
import { Route as AuthenticatedPatientBookRouteImport } from './routes/_authenticated/patient.book'
import { Route as AuthenticatedPatientHistoryRouteImport } from './routes/_authenticated/patient.history'
import { Route as AuthenticatedPatientProfileRouteImport } from './routes/_authenticated/patient.profile'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedStaffPhotosRouteImport } from './routes/_authenticated/staff.photos'
import { Route as AuthenticatedDoctorVisitIdRouteImport } from './routes/_authenticated/doctor.visit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientRoute = AuthenticatedPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDoctorIndexRoute =
  AuthenticatedDoctorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorEmergencyRoute =
  AuthenticatedDoctorEmergencyRouteImport.update({
    id: '/emergency',
    path: '/emergency',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedPatientIndexRoute =
  AuthenticatedPatientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientBookRoute =
  AuthenticatedPatientBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientHistoryRoute =
  AuthenticatedPatientHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientProfileRoute =
  AuthenticatedPatientProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffPhotosRoute =
  AuthenticatedStaffPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedDoctorVisitIdRoute =
  AuthenticatedDoctorVisitIdRouteImport.update({
    id: '/visit/$id',
    path: '/visit/$id',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/patient': typeof AuthenticatedPatientRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/doctor/emergency': typeof AuthenticatedDoctorEmergencyRoute
  '/patient/book': typeof AuthenticatedPatientBookRoute
  '/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/staff/photos': typeof AuthenticatedStaffPhotosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/patient/': typeof AuthenticatedPatientIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/doctor/visit/$id': typeof AuthenticatedDoctorVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/doctor/emergency': typeof AuthenticatedDoctorEmergencyRoute
  '/patient/book': typeof AuthenticatedPatientBookRoute
  '/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/staff/photos': typeof AuthenticatedStaffPhotosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/doctor': typeof AuthenticatedDoctorIndexRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/doctor/visit/$id': typeof AuthenticatedDoctorVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/_authenticated/patient': typeof AuthenticatedPatientRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/doctor/emergency': typeof AuthenticatedDoctorEmergencyRoute
  '/_authenticated/patient/book': typeof AuthenticatedPatientBookRoute
  '/_authenticated/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/_authenticated/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/_authenticated/staff/photos': typeof AuthenticatedStaffPhotosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/_authenticated/patient/': typeof AuthenticatedPatientIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/doctor/visit/$id': typeof AuthenticatedDoctorVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/staff'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/people'
    | '/admin/settings'
    | '/doctor/emergency'
    | '/patient/book'
    | '/patient/history'
    | '/patient/profile'
    | '/staff/photos'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/staff/'
    | '/doctor/visit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/people'
    | '/admin/settings'
    | '/doctor/emergency'
    | '/patient/book'
    | '/patient/history'
    | '/patient/profile'
    | '/staff/photos'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/staff'
    | '/doctor/visit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/doctor'
    | '/_authenticated/patient'
    | '/_authenticated/staff'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/settings'
    | '/_authenticated/doctor/emergency'
    | '/_authenticated/patient/book'
    | '/_authenticated/patient/history'
    | '/_authenticated/patient/profile'
    | '/_authenticated/staff/photos'
    | '/_authenticated/admin/'
    | '/_authenticated/doctor/'
    | '/_authenticated/patient/'
    | '/_authenticated/staff/'
    | '/_authenticated/doctor/visit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient': {
      id: '/_authenticated/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/doctor/': {
      id: '/_authenticated/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof AuthenticatedDoctorIndexRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/emergency': {
      id: '/_authenticated/doctor/emergency'
      path: '/emergency'
      fullPath: '/doctor/emergency'
      preLoaderRoute: typeof AuthenticatedDoctorEmergencyRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/patient/': {
      id: '/_authenticated/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof AuthenticatedPatientIndexRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/book': {
      id: '/_authenticated/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof AuthenticatedPatientBookRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/history': {
      id: '/_authenticated/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof AuthenticatedPatientHistoryRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/profile': {
      id: '/_authenticated/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof AuthenticatedPatientProfileRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/photos': {
      id: '/_authenticated/staff/photos'
      path: '/photos'
      fullPath: '/staff/photos'
      preLoaderRoute: typeof AuthenticatedStaffPhotosRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/doctor/visit/$id': {
      id: '/_authenticated/doctor/visit/$id'
      path: '/visit/$id'
      fullPath: '/doctor/visit/$id'
      preLoaderRoute: typeof AuthenticatedDoctorVisitIdRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDoctorRouteChildren {
  AuthenticatedDoctorEmergencyRoute: typeof AuthenticatedDoctorEmergencyRoute
  AuthenticatedDoctorIndexRoute: typeof AuthenticatedDoctorIndexRoute
  AuthenticatedDoctorVisitIdRoute: typeof AuthenticatedDoctorVisitIdRoute
}

const AuthenticatedDoctorRouteChildren: AuthenticatedDoctorRouteChildren = {
  AuthenticatedDoctorEmergencyRoute: AuthenticatedDoctorEmergencyRoute,
  AuthenticatedDoctorIndexRoute: AuthenticatedDoctorIndexRoute,
  AuthenticatedDoctorVisitIdRoute: AuthenticatedDoctorVisitIdRoute,
}

const AuthenticatedDoctorRouteWithChildren =
  AuthenticatedDoctorRoute._addFileChildren(AuthenticatedDoctorRouteChildren)

interface AuthenticatedPatientRouteChildren {
  AuthenticatedPatientBookRoute: typeof AuthenticatedPatientBookRoute
  AuthenticatedPatientHistoryRoute: typeof AuthenticatedPatientHistoryRoute
  AuthenticatedPatientProfileRoute: typeof AuthenticatedPatientProfileRoute
  AuthenticatedPatientIndexRoute: typeof AuthenticatedPatientIndexRoute
}

const AuthenticatedPatientRouteChildren: AuthenticatedPatientRouteChildren = {
  AuthenticatedPatientBookRoute: AuthenticatedPatientBookRoute,
  AuthenticatedPatientHistoryRoute: AuthenticatedPatientHistoryRoute,
  AuthenticatedPatientProfileRoute: AuthenticatedPatientProfileRoute,
  AuthenticatedPatientIndexRoute: AuthenticatedPatientIndexRoute,
}

const AuthenticatedPatientRouteWithChildren =
  AuthenticatedPatientRoute._addFileChildren(AuthenticatedPatientRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffPhotosRoute: typeof AuthenticatedStaffPhotosRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffPhotosRoute: AuthenticatedStaffPhotosRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRouteWithChildren
  AuthenticatedPatientRoute: typeof AuthenticatedPatientRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRouteWithChildren,
  AuthenticatedPatientRoute: AuthenticatedPatientRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
