/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedPatientRouteImport } from './routes/_authenticated/patient'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedPatientIndexRouteImport } from './routes/_authenticated/patient.index'
import { Route as AuthenticatedPatientBookRouteImport } from './routes/_authenticated/patient.book'
import { Route as AuthenticatedPatientHistoryRouteImport } from './routes/_authenticated/patient.history'
import { Route as AuthenticatedPatientProfileRouteImport } from './routes/_authenticated/patient.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientRoute = AuthenticatedPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientIndexRoute =
  AuthenticatedPatientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientBookRoute =
  AuthenticatedPatientBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientHistoryRoute =
  AuthenticatedPatientHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientProfileRoute =
  AuthenticatedPatientProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/patient': typeof AuthenticatedPatientRouteWithChildren
  '/staff': typeof AuthenticatedStaffRoute
  '/patient/book': typeof AuthenticatedPatientBookRoute
  '/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/patient/': typeof AuthenticatedPatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/patient/book': typeof AuthenticatedPatientBookRoute
  '/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/patient': typeof AuthenticatedPatientRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/patient/book': typeof AuthenticatedPatientBookRoute
  '/_authenticated/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/_authenticated/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/_authenticated/patient/': typeof AuthenticatedPatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/staff'
    | '/patient/book'
    | '/patient/history'
    | '/patient/profile'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/doctor'
    | '/staff'
    | '/patient/book'
    | '/patient/history'
    | '/patient/profile'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/doctor'
    | '/_authenticated/patient'
    | '/_authenticated/staff'
    | '/_authenticated/patient/book'
    | '/_authenticated/patient/history'
    | '/_authenticated/patient/profile'
    | '/_authenticated/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient': {
      id: '/_authenticated/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/': {
      id: '/_authenticated/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof AuthenticatedPatientIndexRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/book': {
      id: '/_authenticated/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof AuthenticatedPatientBookRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/history': {
      id: '/_authenticated/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof AuthenticatedPatientHistoryRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/profile': {
      id: '/_authenticated/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof AuthenticatedPatientProfileRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
  }
}

interface AuthenticatedPatientRouteChildren {
  AuthenticatedPatientBookRoute: typeof AuthenticatedPatientBookRoute
  AuthenticatedPatientHistoryRoute: typeof AuthenticatedPatientHistoryRoute
  AuthenticatedPatientProfileRoute: typeof AuthenticatedPatientProfileRoute
  AuthenticatedPatientIndexRoute: typeof AuthenticatedPatientIndexRoute
}

const AuthenticatedPatientRouteChildren: AuthenticatedPatientRouteChildren = {
  AuthenticatedPatientBookRoute: AuthenticatedPatientBookRoute,
  AuthenticatedPatientHistoryRoute: AuthenticatedPatientHistoryRoute,
  AuthenticatedPatientProfileRoute: AuthenticatedPatientProfileRoute,
  AuthenticatedPatientIndexRoute: AuthenticatedPatientIndexRoute,
}

const AuthenticatedPatientRouteWithChildren =
  AuthenticatedPatientRoute._addFileChildren(AuthenticatedPatientRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedPatientRoute: typeof AuthenticatedPatientRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedPatientRoute: AuthenticatedPatientRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
